name: Release P2 repository

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Configure Git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - name: Build with Maven
      run: >
        mvn deploy
        -Prelease-composite
        -Dgithub-update-repo=https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/SeineEloquenz/p2
